import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        tertiary: "#b9c7e0",
        "primary-fixed-dim": "#ffb3b1",
        "on-primary-fixed-variant": "#92001c",
        "secondary-fixed-dim": "#c4c7c9",
        "on-surface-variant": "#e4bebc",
        "on-error": "#690005",
        "on-background": "#dae2fd",
        "secondary-container": "#464a4b",
        "on-primary-fixed": "#410007",
        "surface-tint": "#ffb3b1",
        "on-secondary-container": "#b6b9bb",
        "secondary-fixed": "#e0e3e5",
        "primary-fixed": "#ffdad8",
        "on-tertiary-fixed": "#0d1c2f",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "on-primary-container": "#5b000e",
        "on-secondary": "#2d3133",
        "surface-container-low": "#131b2e",
        "surface-bright": "#31394d",
        "surface-container-high": "#222a3d",
        "inverse-surface": "#dae2fd",
        "on-secondary-fixed": "#191c1e",
        "secondary": "#c4c7c9",
        primary: "#ffb3b1",
        "tertiary-container": "#8392a9",
        "inverse-primary": "#bb162c",
        "on-tertiary-container": "#1c2a3d",
        "surface-dim": "#0b1326",
        "tertiary-fixed": "#d5e3fd",
        "on-tertiary-fixed-variant": "#3a485c",
        "on-secondary-fixed-variant": "#444749",
        surface: "#0b1326",
        "surface-container": "#171f33",
        "surface-container-lowest": "#060e20",
        error: "#ffb4ab",
        outline: "#ab8987",
        "tertiary-fixed-dim": "#b9c7e0",
        "surface-variant": "#2d3449",
        "on-surface": "#dae2fd",
        "on-tertiary": "#233144",
        "on-primary": "#680011",
        background: "#0b1326",
        "surface-container-highest": "#2d3449",
        "primary-container": "#ff535a",
        "inverse-on-surface": "#283044",
        "outline-variant": "#5b403f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "0.5rem",
        "stack-lg": "2rem",
        gutter: "1.5rem",
        "container-padding-desktop": "2.5rem",
        "container-padding-mobile": "1rem",
        unit: "4px",
        "stack-md": "1rem",
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "interactive-label": ["Outfit", "sans-serif"],
        "display-lg-mobile": ["Outfit", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "display-lg": ["Outfit", "sans-serif"],
        "headline-md": ["Outfit", "sans-serif"],
      },
    },
  },
  plugins: [],
};
export default config;
